Updated: 12.10.2024 12:37

diff --git a/Linux (3) b/Linux (3)
--- a/Linux (3)
+++ b/Linux (3)
@@ -140,7 +140,63 @@ Bash поддерживает выполнение простейших опер
  let result="5 * 2"
  echo $result
 
-Условия и команда test...
+Команда test проверяет соответсвие некоторому условию:
+
+ * test $var - определена ли переменная $var;
+ * test -e $var - является ли $var файлом;
+
+ * test -f $var - является ли $var обычный файлом (а не файлом устройства, 
+   каталогом или исполняемым файлом);
+
+ * test -d $var - является ли $var каталогом;
+ * test -x $var - является ли $var исполняемым файлом;
+ * test $var1 -nt $var2 - явяется ли $var1 новее, чем $var2;
+ * test $var1 -ot $var2 - старше ли $var1, чем $var2;
+ * test $var1 -eq $var2 - равны ли числа $var и $var2;
+ * test $var1 -ne $var2 - не равны ли числа $var1 и $var2;
+ * test $var1 -gt $var2 - больше ли число $var1 чем $var2;
+ * test $var1 -lt $var2 - меньше ли число $var1 чем $var2;
+ * test $var1 -ge $var2 - является ли число $var1 большим или равным $var2;
+ * test $var1 -le $var2 - является ли число $var1 меньшим или равным $var2;
+ 
+ * test $var1 = $var2 - сопвадают ли строки $var1 и $var2; также применяется 
+   для сравнения значений 2х переменных;
+
+ * test $var1 != $var2 - не равны ли строки $var1 и $var2; знак "!" можно использовать 
+   со всеми другими командами test, а также для проверки отрицательного утверждения. 
+
+Также для проверки можно использовать сокращенную форму, при которой вся команда 
+помещается в квадратные скобки (с пробелами), а слово test опускается:
+
+ [ -f $1 ]  (тоже самое что и test -f $1)
+
+С помощью операторов && и || можно объединять проверки и различные команды:
+
+ [ -f $path ] && echo "$path is a file"  (веведет строку, если $path явл. файлом)
+
+ mkdir ~/Documents/test && echo "Folder created!"  (выводится сообщение, если папка
+                         test успешно создана в домашнем каталоге пользователя; но если 
+                         папку не удастся создать, тогда вторая команда не выполнется).
+ 
+ mkdir ~/Documents/test || echo "Unable to create"  (наоборот, выполнит вторую команду, 
+                  если не удалось выполнить первую; например, когда папка уже существует).
+
+Условная конструкция if/else выглядит так:
+
+ if [ $a -eq $b ]          if [ $a -eq $b ]             if [ $a -gt $b ]
+ then                      then                         then
+     echo "a и b равны"        echo "числа равны"           echo "a больше b"
+ fi                        else                         elif [ $a -lt $b ]
+                               echo "числа не равны"    then
+                           fi                               echo "a меньше b"
+                                                        else
+                                                            echo "a и b равны"
+                                                        fi
+
+После if/elif указывается условие, а после then - набор команд. 
+Заканчивается вся конструкция словом fi.
+
+Конструкция case...
 
 ---------------
 
